apiVersion: apps/v1
kind: Deployment
metadata:
  name: countcluster-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: countcluster-app
  template:
    metadata:
      labels:
        app: countcluster-app
    spec:
      serviceAccountName: k8s-101-role
      containers:
      - name: countcluster-app
        image: vikasit/countcluster:v1
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: countcluster-service
spec:
  selector:
    app: countcluster-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-101-role
subjects:
  - kind: ServiceAccount
    name: k8s-101-role
    namespace: 108-test
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-101-role
